import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="resume-navbar">
          <div className="resume-navbar__brand">
            <span style={{fontSize: 28, color: '#4F46E5'}}>✦</span>
            <span>ResumeAI</span>
          </div>
          <nav className="resume-nav-links">
            <Link href="/resume-input" className="resume-nav-link">Resume Input</Link>
            <Link href="/resume-editor" className="resume-nav-link">Resume Editor</Link>
            {/* Export Versions link removed */}
          </nav>
        </header>
        <main className="app-main">{children}</main>
      </body>
    </html>
  );
}
